
[items]
	#List of cosmetic-only items. All items in this list will have their effects disabled
	#To blacklist all items, use "artifacts:*"
	#Note: blacklisting an item while it is equipped may have unintended side effects
	cosmetics = [""]

	[items.antidote_vessel]
		#Affects how many times a negative effect can be shortened before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#The maximum duration (in ticks) a negative effect can last with the antidote vessel equipped
		#Range: > 0
		max_effect_duration = 120

	[items.aqua_dashers]
		#Affects how many seconds the player can run on fluids using the aqua dashers before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0

	[items.bunny_hoppers]
		#Affects how many times the player can jump with the bunny hoppers before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Whether Bunny Hoppers should cancel fall damage
		#Fall damage will still be reduced by the jump boost effect
		should_cancel_fall_damage = true
		#The level of the jump boost effect applied by the bunny hoppers
		#0 to not apply a jump boost effect
		#Range: 0 ~ 128
		jump_boost_level = 2

	[items.cross_necklace]
		#Affects how many times the player can take damage with the cross necklace before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#The amount of additional ticks the wearer is invincible after being hit
		#Range: > 0
		invincibility_bonus = 20

	[items.crystal_heart]
		#Affects how much damage the player can take while wearing the crystal heart before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#The amount additional health applied to the wearer
		#Range: > 0
		health_bonus = 5

	[items.digging_claws]
		#Affects how many blocks the player can break using the digging claws before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Mining speed bonus applied by digging claws
		#Range: 0.0 ~ Infinity
		mining_speed_bonus = 3.2
		#The tool tier of the digging claws
		#To modify mineable blocks, use the 'artifacts:mineable/digging_claws' block tag
		tool_tier = "minecraft:stone"

	[items.feral_claws]
		#Affects how many enemies can be hit using the feral claws before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Attack speed bonus applied by feral claws
		#Range: 0.0 ~ Infinity
		attack_speed_bonus = 0.75

	[items.flame_pendant]
		#Affects how many times the pendant's effect can be applied before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Chance for the pendant to strike an attacker when the wearer is attacked
		#Range: 0.0 ~ 1.0
		strike_chance = 0.4
		#Duration (equal to total fire damage) for which entities are set on fire
		#Range: > 0
		fire_duration = 10

	[items.flippers]
		#Affects how many seconds the player can swim using the flippers
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Swim speed bonus applied by flippers
		#Range: 0.0 ~ Infinity
		swim_speed_bonus = 1.0

	[items.golden_hook]
		#Affects how many enemies can be killed using the golden hook before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#The amount of extra experience (multiplied with total xp) entities should drop when killed by a player wearing the golden hook
		#Range: 0.0 ~ Infinity
		experience_bonus = 0.75

	[items.kitty_slippers]
		#Affects how many creepers the player can attack using the kitty slippers before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0

	[items.lucky_scarf]
		#Affects how many blocks can be broken using the lucky scarf
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Fortune bonus applied by the lucky scarf
		#Range: > 0
		fortune_bonus = 1

	[items.night_vision_goggles]
		#Affects how many seconds the night vision effect should apply before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0

	[items.panic_necklace]
		#Affects how many times the necklace's effect can be applied
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#The level of the speed effect applied by the panic necklace
		#Range: 0 ~ 128
		speed_level = 1
		#The duration (in ticks) of the speed effect applied by the panic necklace
		#Range: > 0
		speed_duration = 160

	[items.plastic_drinking_hat]
		#Affects how many items the player can drink or eat using the drinking hat before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Drinking duration multiplier applied by the drinking hat
		#Range: 0.0 ~ Infinity
		drinking_duration_multiplier = 0.3
		#Eating duration multiplier applied by the drinking hat
		#Range: 0.0 ~ Infinity
		eating_duration_multiplier = 0.6

	[items.pocket_piston]
		#Affects how many enemies can be hit using the pocket piston
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#The amount of extra knockback applied by the pocket piston
		#Range: 0.0 ~ Infinity
		knockback_bonus = 1.5

	[items.power_glove]
		#Affects how many enemies can be hit using the power glove
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#The amount of extra attack damage applied by the power glove
		#Range: > 0
		attack_damage_bonus = 4

	[items.running_shoes]
		#Affects how many seconds the player can sprint using the running shoes
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#The amount of extra speed applied by the running shoes
		#Range: 0.0 ~ Infinity
		speed_multiplier = 0.4

	[items.shock_pendant]
		#Affects how many times the pendant's effect can be applied before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Chance for the pendant to strike an attacker when the wearer is attacked
		#Range: 0.0 ~ 1.0
		strike_chance = 0.25

	[items.steadfast_spikes]
		#Affects how many times the player can be hit while wearing steadfast spikes before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0

	[items.superstitious_hat]
		#Affects how many enemies can be killed using the superstitious hat
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Looting bonus applied by the superstitious hat
		#Range: > 0
		looting_bonus = 1

	[items.thorn_pendant]
		#Affects how many times the pendant's effect can be applied before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Chance for the pendant to strike an attacker when the wearer is attacked
		#Range: 0.0 ~ 1.0
		strike_chance = 0.5
		#Minimum damage dealt by thorn pendant
		#Damage dealt is a random number between min_damage and max_damage
		#Range: > 0
		min_damage = 2
		#Maximum damage dealt by thorn pendant
		#Range: > 0
		max_damage = 6

	[items.villager_hat]
		#Affects how many trades can be completed using the villager hat
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Affects how much prices are reduced by the villager hat
		#Range: > 0
		reputation_bonus = 100

