[[curiosSettings]]
  identifier = "head"
  visible = true
  override = true

[[curiosSettings]]
  identifier = "necklace"
  visible = true
  override = true
  
[[curiosSettings]]
  identifier = "back"
  override = true
  visible = true

[[curiosSettings]]
  identifier = "hands"
  override = true
  visible = true

[[curiosSettings]]
  identifier = "ring"
  override = true
  visible = true
  size = 2