
#Modify the value of the weapons and tools using the custom material.
[material_setting]

	[material_setting.tin_settings]
		#Enable the crafting of tool made of tin
		enable_crafting = false

		[material_setting.tin_settings.tin_tool_settings]
			#Set the damage modifier of the tool with the tin
			#Range: -10000.0 ~ 10000.0
			damage = 0.0
			#Set the tool level modifier of the tool with the tin
			#Range: -10000 ~ 10000
			tool_level = 0
			#Set the number of use of the tool with the tin
			#Range: -10000 ~ 10000
			number_of_use = 0
			#Set the block breaking speed modifier of the tool with the tin
			#Range: -10000.0 ~ 10000.0
			block_speed = 0.0
			#Set the enchantment modifier of the tool with the tin
			#Range: -10000 ~ 10000
			enchantment = 0

		[material_setting.tin_settings.tin_armor_settings]
			#Set the helmet durability modifier of the tool with the tin
			#Range: -10000 ~ 10000
			helmet_durability = 0
			#Set the chestplate durability modifier of the tool with the tin
			#Range: -10000 ~ 10000
			chestplate_durability = 0
			#Set the leggings durability modifier of the tool with the tin
			#Range: -10000 ~ 10000
			leggings_durability = 0
			#Set the boots durability modifier of the tool with the tin
			#Range: -10000 ~ 10000
			boots_durability = 0
			#Set the helmet protection modifier of the tool with the tin
			#Range: -10000 ~ 10000
			helmet_protection = 0
			#Set the chestplate protection modifier of the tool with the tin
			#Range: -10000 ~ 10000
			chestplate_protection = 0
			#Set the leggings protection modifier of the tool with the tin
			#Range: -10000 ~ 10000
			leggings_protection = 0
			#Set the boots protection modifier of the tool with the tin
			#Range: -10000 ~ 10000
			boots_protection = 0
			#Set the enchantment modifier of the tool with the tin
			#Range: -10000 ~ 10000
			enchantment = 0
			#Set the toughness modifier of the tool with the tin
			#Range: -10000.0 ~ 10000.0
			toughness = 0.0
			#Set the knockback resistance modifier of the tool with the tin
			#Range: -10000.0 ~ 10000.0
			knockback_res = 0.0

	[material_setting.zinc_settings]
		#Enable the crafting of tool made of zinc
		enable_crafting = false

		[material_setting.zinc_settings.zinc_tool_settings]
			#Set the damage modifier of the tool with the zinc
			#Range: -10000.0 ~ 10000.0
			damage = 0.0
			#Set the tool level modifier of the tool with the zinc
			#Range: -10000 ~ 10000
			tool_level = 0
			#Set the number of use of the tool with the zinc
			#Range: -10000 ~ 10000
			number_of_use = 0
			#Set the block breaking speed modifier of the tool with the zinc
			#Range: -10000.0 ~ 10000.0
			block_speed = 0.0
			#Set the enchantment modifier of the tool with the zinc
			#Range: -10000 ~ 10000
			enchantment = 0

		[material_setting.zinc_settings.zinc_armor_settings]
			#Set the helmet durability modifier of the tool with the zinc
			#Range: -10000 ~ 10000
			helmet_durability = 0
			#Set the chestplate durability modifier of the tool with the zinc
			#Range: -10000 ~ 10000
			chestplate_durability = 0
			#Set the leggings durability modifier of the tool with the zinc
			#Range: -10000 ~ 10000
			leggings_durability = 0
			#Set the boots durability modifier of the tool with the zinc
			#Range: -10000 ~ 10000
			boots_durability = 0
			#Set the helmet protection modifier of the tool with the zinc
			#Range: -10000 ~ 10000
			helmet_protection = 0
			#Set the chestplate protection modifier of the tool with the zinc
			#Range: -10000 ~ 10000
			chestplate_protection = 0
			#Set the leggings protection modifier of the tool with the zinc
			#Range: -10000 ~ 10000
			leggings_protection = 0
			#Set the boots protection modifier of the tool with the zinc
			#Range: -10000 ~ 10000
			boots_protection = 0
			#Set the enchantment modifier of the tool with the zinc
			#Range: -10000 ~ 10000
			enchantment = 0
			#Set the toughness modifier of the tool with the zinc
			#Range: -10000.0 ~ 10000.0
			toughness = 0.0
			#Set the knockback resistance modifier of the tool with the zinc
			#Range: -10000.0 ~ 10000.0
			knockback_res = 0.0

	[material_setting.copper_settings]
		#Enable the crafting of tool made of copper
		enable_crafting = false

		[material_setting.copper_settings.copper_tool_settings]
			#Set the damage modifier of the tool with the copper
			#Range: -10000.0 ~ 10000.0
			damage = 0.0
			#Set the tool level modifier of the tool with the copper
			#Range: -10000 ~ 10000
			tool_level = 0
			#Set the number of use of the tool with the copper
			#Range: -10000 ~ 10000
			number_of_use = 0
			#Set the block breaking speed modifier of the tool with the copper
			#Range: -10000.0 ~ 10000.0
			block_speed = 0.0
			#Set the enchantment modifier of the tool with the copper
			#Range: -10000 ~ 10000
			enchantment = 0

		[material_setting.copper_settings.copper_armor_settings]
			#Set the helmet durability modifier of the tool with the copper
			#Range: -10000 ~ 10000
			helmet_durability = 0
			#Set the chestplate durability modifier of the tool with the copper
			#Range: -10000 ~ 10000
			chestplate_durability = 0
			#Set the leggings durability modifier of the tool with the copper
			#Range: -10000 ~ 10000
			leggings_durability = 0
			#Set the boots durability modifier of the tool with the copper
			#Range: -10000 ~ 10000
			boots_durability = 0
			#Set the helmet protection modifier of the tool with the copper
			#Range: -10000 ~ 10000
			helmet_protection = 0
			#Set the chestplate protection modifier of the tool with the copper
			#Range: -10000 ~ 10000
			chestplate_protection = 0
			#Set the leggings protection modifier of the tool with the copper
			#Range: -10000 ~ 10000
			leggings_protection = 0
			#Set the boots protection modifier of the tool with the copper
			#Range: -10000 ~ 10000
			boots_protection = 0
			#Set the enchantment modifier of the tool with the copper
			#Range: -10000 ~ 10000
			enchantment = 0
			#Set the toughness modifier of the tool with the copper
			#Range: -10000.0 ~ 10000.0
			toughness = 0.0
			#Set the knockback resistance modifier of the tool with the copper
			#Range: -10000.0 ~ 10000.0
			knockback_res = 0.0

	[material_setting.brass_settings]
		#Enable the crafting of tool made of brass
		enable_crafting = false

		[material_setting.brass_settings.brass_tool_settings]
			#Set the damage modifier of the tool with the brass
			#Range: -10000.0 ~ 10000.0
			damage = 0.0
			#Set the tool level modifier of the tool with the brass
			#Range: -10000 ~ 10000
			tool_level = 0
			#Set the number of use of the tool with the brass
			#Range: -10000 ~ 10000
			number_of_use = 0
			#Set the block breaking speed modifier of the tool with the brass
			#Range: -10000.0 ~ 10000.0
			block_speed = 0.0
			#Set the enchantment modifier of the tool with the brass
			#Range: -10000 ~ 10000
			enchantment = 0

		[material_setting.brass_settings.brass_armor_settings]
			#Set the helmet durability modifier of the tool with the brass
			#Range: -10000 ~ 10000
			helmet_durability = 0
			#Set the chestplate durability modifier of the tool with the brass
			#Range: -10000 ~ 10000
			chestplate_durability = 0
			#Set the leggings durability modifier of the tool with the brass
			#Range: -10000 ~ 10000
			leggings_durability = 0
			#Set the boots durability modifier of the tool with the brass
			#Range: -10000 ~ 10000
			boots_durability = 0
			#Set the helmet protection modifier of the tool with the brass
			#Range: -10000 ~ 10000
			helmet_protection = 0
			#Set the chestplate protection modifier of the tool with the brass
			#Range: -10000 ~ 10000
			chestplate_protection = 0
			#Set the leggings protection modifier of the tool with the brass
			#Range: -10000 ~ 10000
			leggings_protection = 0
			#Set the boots protection modifier of the tool with the brass
			#Range: -10000 ~ 10000
			boots_protection = 0
			#Set the enchantment modifier of the tool with the brass
			#Range: -10000 ~ 10000
			enchantment = 0
			#Set the toughness modifier of the tool with the brass
			#Range: -10000.0 ~ 10000.0
			toughness = 0.0
			#Set the knockback resistance modifier of the tool with the brass
			#Range: -10000.0 ~ 10000.0
			knockback_res = 0.0

	[material_setting.bronze_settings]
		#Enable the crafting of tool made of bronze
		enable_crafting = false

		[material_setting.bronze_settings.bronze_tool_settings]
			#Set the damage modifier of the tool with the bronze
			#Range: -10000.0 ~ 10000.0
			damage = 0.0
			#Set the tool level modifier of the tool with the bronze
			#Range: -10000 ~ 10000
			tool_level = 0
			#Set the number of use of the tool with the bronze
			#Range: -10000 ~ 10000
			number_of_use = 0
			#Set the block breaking speed modifier of the tool with the bronze
			#Range: -10000.0 ~ 10000.0
			block_speed = 0.0
			#Set the enchantment modifier of the tool with the bronze
			#Range: -10000 ~ 10000
			enchantment = 0

		[material_setting.bronze_settings.bronze_armor_settings]
			#Set the helmet durability modifier of the tool with the bronze
			#Range: -10000 ~ 10000
			helmet_durability = 0
			#Set the chestplate durability modifier of the tool with the bronze
			#Range: -10000 ~ 10000
			chestplate_durability = 0
			#Set the leggings durability modifier of the tool with the bronze
			#Range: -10000 ~ 10000
			leggings_durability = 0
			#Set the boots durability modifier of the tool with the bronze
			#Range: -10000 ~ 10000
			boots_durability = 0
			#Set the helmet protection modifier of the tool with the bronze
			#Range: -10000 ~ 10000
			helmet_protection = 0
			#Set the chestplate protection modifier of the tool with the bronze
			#Range: -10000 ~ 10000
			chestplate_protection = 0
			#Set the leggings protection modifier of the tool with the bronze
			#Range: -10000 ~ 10000
			leggings_protection = 0
			#Set the boots protection modifier of the tool with the bronze
			#Range: -10000 ~ 10000
			boots_protection = 0
			#Set the enchantment modifier of the tool with the bronze
			#Range: -10000 ~ 10000
			enchantment = 0
			#Set the toughness modifier of the tool with the bronze
			#Range: -10000.0 ~ 10000.0
			toughness = 0.0
			#Set the knockback resistance modifier of the tool with the bronze
			#Range: -10000.0 ~ 10000.0
			knockback_res = 0.0

	[material_setting.rosegold_settings]
		#Enable the crafting of tool made of rosegold
		enable_crafting = false

		[material_setting.rosegold_settings.rosegold_tool_settings]
			#Set the damage modifier of the tool with the rosegold
			#Range: -10000.0 ~ 10000.0
			damage = 0.0
			#Set the tool level modifier of the tool with the rosegold
			#Range: -10000 ~ 10000
			tool_level = 0
			#Set the number of use of the tool with the rosegold
			#Range: -10000 ~ 10000
			number_of_use = 0
			#Set the block breaking speed modifier of the tool with the rosegold
			#Range: -10000.0 ~ 10000.0
			block_speed = 0.0
			#Set the enchantment modifier of the tool with the rosegold
			#Range: -10000 ~ 10000
			enchantment = 0

		[material_setting.rosegold_settings.rosegold_armor_settings]
			#Set the helmet durability modifier of the tool with the rosegold
			#Range: -10000 ~ 10000
			helmet_durability = 0
			#Set the chestplate durability modifier of the tool with the rosegold
			#Range: -10000 ~ 10000
			chestplate_durability = 0
			#Set the leggings durability modifier of the tool with the rosegold
			#Range: -10000 ~ 10000
			leggings_durability = 0
			#Set the boots durability modifier of the tool with the rosegold
			#Range: -10000 ~ 10000
			boots_durability = 0
			#Set the helmet protection modifier of the tool with the rosegold
			#Range: -10000 ~ 10000
			helmet_protection = 0
			#Set the chestplate protection modifier of the tool with the rosegold
			#Range: -10000 ~ 10000
			chestplate_protection = 0
			#Set the leggings protection modifier of the tool with the rosegold
			#Range: -10000 ~ 10000
			leggings_protection = 0
			#Set the boots protection modifier of the tool with the rosegold
			#Range: -10000 ~ 10000
			boots_protection = 0
			#Set the enchantment modifier of the tool with the rosegold
			#Range: -10000 ~ 10000
			enchantment = 0
			#Set the toughness modifier of the tool with the rosegold
			#Range: -10000.0 ~ 10000.0
			toughness = 0.0
			#Set the knockback resistance modifier of the tool with the rosegold
			#Range: -10000.0 ~ 10000.0
			knockback_res = 0.0

	[material_setting.steel_settings]
		#Enable the crafting of tool made of steel
		enable_crafting = false

		[material_setting.steel_settings.steel_tool_settings]
			#Set the damage modifier of the tool with the steel
			#Range: -10000.0 ~ 10000.0
			damage = 0.0
			#Set the tool level modifier of the tool with the steel
			#Range: -10000 ~ 10000
			tool_level = 0
			#Set the number of use of the tool with the steel
			#Range: -10000 ~ 10000
			number_of_use = 0
			#Set the block breaking speed modifier of the tool with the steel
			#Range: -10000.0 ~ 10000.0
			block_speed = 0.0
			#Set the enchantment modifier of the tool with the steel
			#Range: -10000 ~ 10000
			enchantment = 0

		[material_setting.steel_settings.steel_armor_settings]
			#Set the helmet durability modifier of the tool with the steel
			#Range: -10000 ~ 10000
			helmet_durability = 0
			#Set the chestplate durability modifier of the tool with the steel
			#Range: -10000 ~ 10000
			chestplate_durability = 0
			#Set the leggings durability modifier of the tool with the steel
			#Range: -10000 ~ 10000
			leggings_durability = 0
			#Set the boots durability modifier of the tool with the steel
			#Range: -10000 ~ 10000
			boots_durability = 0
			#Set the helmet protection modifier of the tool with the steel
			#Range: -10000 ~ 10000
			helmet_protection = 0
			#Set the chestplate protection modifier of the tool with the steel
			#Range: -10000 ~ 10000
			chestplate_protection = 0
			#Set the leggings protection modifier of the tool with the steel
			#Range: -10000 ~ 10000
			leggings_protection = 0
			#Set the boots protection modifier of the tool with the steel
			#Range: -10000 ~ 10000
			boots_protection = 0
			#Set the enchantment modifier of the tool with the steel
			#Range: -10000 ~ 10000
			enchantment = 0
			#Set the toughness modifier of the tool with the steel
			#Range: -10000.0 ~ 10000.0
			toughness = 0.0
			#Set the knockback resistance modifier of the tool with the steel
			#Range: -10000.0 ~ 10000.0
			knockback_res = 0.0

#Modify the value of the new added weapon.
[weapon_setting]

	[weapon_setting.battlestaff_settings]
		#Enable the crafting of tool made of battlestaff
		Enable = true
		#Set the attack damage modifier of the battlestaff
		#Range: -10000.0 ~ 10000.0
		"Damage modifier" = 0.0
		#Set the attack speed modifier of the battlestaff
		#Range: -10000.0 ~ 10000.0
		"Attack speed modifier" = 0.0

	[weapon_setting.glaive_settings]
		#Enable the crafting of tool made of glaive
		Enable = true
		#Set the attack damage modifier of the glaive
		#Range: -10000.0 ~ 10000.0
		"Damage modifier" = 0.0
		#Set the attack speed modifier of the glaive
		#Range: -10000.0 ~ 10000.0
		"Attack speed modifier" = 0.0

	[weapon_setting.greataxe_settings]
		#Enable the crafting of tool made of greataxe
		Enable = true
		#Set the attack damage modifier of the greataxe
		#Range: -10000.0 ~ 10000.0
		"Damage modifier" = 0.0
		#Set the attack speed modifier of the greataxe
		#Range: -10000.0 ~ 10000.0
		"Attack speed modifier" = 0.0

	[weapon_setting.greatsword_settings]
		#Enable the crafting of tool made of greatsword
		Enable = true
		#Set the attack damage modifier of the greatsword
		#Range: -10000.0 ~ 10000.0
		"Damage modifier" = 0.0
		#Set the attack speed modifier of the greatsword
		#Range: -10000.0 ~ 10000.0
		"Attack speed modifier" = 0.0

	[weapon_setting.halberd_settings]
		#Enable the crafting of tool made of halberd
		Enable = true
		#Set the attack damage modifier of the halberd
		#Range: -10000.0 ~ 10000.0
		"Damage modifier" = 0.0
		#Set the attack speed modifier of the halberd
		#Range: -10000.0 ~ 10000.0
		"Attack speed modifier" = 0.0

	[weapon_setting.katana_settings]
		#Enable the crafting of tool made of katana
		Enable = true
		#Set the attack damage modifier of the katana
		#Range: -10000.0 ~ 10000.0
		"Damage modifier" = 0.0
		#Set the attack speed modifier of the katana
		#Range: -10000.0 ~ 10000.0
		"Attack speed modifier" = 0.0

	[weapon_setting.scimitar_settings]
		#Enable the crafting of tool made of scimitar
		Enable = true
		#Set the attack damage modifier of the scimitar
		#Range: -10000.0 ~ 10000.0
		"Damage modifier" = 0.0
		#Set the attack speed modifier of the scimitar
		#Range: -10000.0 ~ 10000.0
		"Attack speed modifier" = 0.0

	[weapon_setting.spear_settings]
		#Enable the crafting of tool made of spear
		Enable = true
		#Set the attack damage modifier of the spear
		#Range: -10000.0 ~ 10000.0
		"Damage modifier" = 0.0
		#Set the attack speed modifier of the spear
		#Range: -10000.0 ~ 10000.0
		"Attack speed modifier" = 0.0

