
[types]

	[types.leaves_type]

		[types.leaves_type.nethers_exoticism]
			jaboticaba = true

		[types.leaves_type.vinery]
			grapevine = true
			cherry = true

		[types.leaves_type.ecologics]
			coconut = true
			walnut = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			pink_blossom = true
			yellow_blossom = true
			red_blossom = true

	[types.wood_type]

		[types.wood_type.nethers_exoticism]
			jabuticaba = true
			ramboutan = true

		[types.wood_type.quark]
			bamboo = true
			azalea = false
			ancient = true
			blossom = true

		[types.wood_type.ecologics]
			flowering_azalea = true
			azalea = true
			coconut = true
			walnut = true

		[types.wood_type.vinery]
			cherry = true

[entries]

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

	[entries.wood_type]

		[entries.wood_type.mcwroofs]
			upper_lower_roof = true
			planks_upper_steep_roof = true
			top_roof = true
			planks_top_roof = true
			lower_roof = true
			planks_steep_roof = true
			planks_roof = true
			attic_roof = true
			upper_steep_roof = true
			planks_upper_lower_roof = true
			steep_roof = true
			roof = true
			planks_lower_roof = true
			planks_attic_roof = true

		[entries.wood_type.another_furniture]
			shelf = true
			shutter = true
			planter_box = true
			bench = true
			table = true
			drawer = true
			chair = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.quark]
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true

		[entries.wood_type.mcwpaths]
			planks_path = true

		[entries.wood_type.dramaticdoors]
			tall_door = true

