storagenetwork = false
tconstruct = false
sophisticatedbackpacks = true
fastfurnace = false
ironfurnaces = false
occultism = false
jei = true
ae2 = false
extendedcrafting = false
refinedstorageaddons = false
craftingcraft = false
toms_storage = true
sophisticatedcore = true
refinedstorage = false
prettypipes = false
fastbench = true
cyclic = false

